### PR TITLE
Get Envelope Documents Combined with query parameters

### PR DESCRIPTION
**Pull request by PatrickHeneise**
[Get Envelope Documents Combined](http://iodocs.docusign.com/#tabEndpoint4Method9) is defined with the parameters `show_changes`, `watermark` and `certificate`, none of them is reflected in the node.js API. With this change the parameters can be modified without breaking the current behaviour of only having 3 arguments in the function definition.

### CODE REVIEW

**Comment by mmallis87** [comment]
@PatrickHeneise Great work! Do you mind following the same logic as EnvelopesApi.createEnvelope, i.e creating a GetDocumentsOptions with the options you've listed and then handling them in getDocuments method. Here is the example:
https://github.com/docusign/docusign-node-client/blob/master/src/api/EnvelopesApi.js#L386
https://github.com/docusign/docusign-node-client/blob/master/src/api/EnvelopesApi.js#L424

The reason for that is to avoid conflict when merging your PR with the auto-generated code from Swagger codegen.

Cheers,
Majid

**Comment by PatrickHeneise** [comment]
@mmallis87 CreateEnvelopeOptions is a function that's not used in the code, so I don't really see a point creating it for getEnvelope? I'm not sure what this all does and I'm not familiar with swagger auto-generated code. The change is a cosmetic change that doesn't break the implementation for anyone else.

**Comment by PatrickHeneise** [comment]
Any issue from merging this?

**Comment by mmallis87** [comment]
Patrick, I understand you're being surprised, but it's really important to follow the coding practices across all the functions of this library, because otherwise it won't be possible to take your merge into account once we generate a new version of the lib.

Basically we use Swagger technology, with some customizations. Which allows us to deliver fast and automated code our of a very large REST API that is the DocuSign Signature API. And to ensure a good code quality (not talking about the ugly syntax of the code), we do run a bunch of unit tests before each release.

I hope this gives you a better idea why I'm kind of picky on the code syntax, even if I know it's ugly. It's the drawback of using a code automation technology that is powerful but still needs to be improved, as you can see.

**Comment by PatrickHeneise** [comment]
@mmallis87, as described initially:

> Get Envelope Documents Combined is defined with the parameters show_changes, watermark and certificate, none of them is reflected in the node.js API

I have no idea about your code generation and honestly, it's not my problem. My problem is that the code doesn't follow the specs described and here's a solution for that to fix the issue. If it's not according to your personal code practises, please fix it - the swagger API tool has those parameters and I need them in my implementation.

**Pull request closed without merging**
